### ISSUE TITLE
Sale Figures for Russia are wrong

### ISSUE THREAD

**Issue by AlexandreMinard** [nicolasgomollon/AppSales-Mobile#12] opened 2016-04-25 14:07 UTC
Hello,

Unfortunately, figures for sales in Russia are totally wrong.
Number of downloads is ok, but revenue associated to them are wrong (1 sale of 2$ is count as $242...)

That would be cool to fix that :)

Regards,
Alexandre

**Comment by ddaddy** [comment] 2016-04-25 14:16
It's an error with Yahoo currency exchange rates.
It's happened before, someone at yahoo puts a decimal point in the wrong place.
Wait until currencies are updated by Yahoo tomorrow and your figures should go back to normal.

**Comment by AlexandreMinard** [comment] 2016-04-25 14:19
ok thanks :)

**Comment by nicolasgomollon** [comment] 2016-04-26 17:13
Duplicate of #7.

**Closed as completed by nicolasgomollon** 2016-04-26 17:13 UTC
Labels: duplicate
